# Generated by Django 5.0.6 on 2024-07-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_movie_description_alter_movie_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
    ]
